version: '3.11.5'

services:
  ibeam:
    image: voyz/ibeam:latest
    container_name: ibeam
    env_file:
      - .env
    ports:
      - 5002:5000
      - 5001:5001
    network_mode: bridge
    restart: 'no'

  sql:
    image: postgres:16.1
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - stock_db:/var/lib/postgresql/data
    restart: unless-stopped

  lean:
    image: quantconnect/lean:latest
    container_name: lean

volumes:
  stock_db: