version: '3.11.5'

services:
  ibeam:
    image: voyz/ibeam
    container_name: ibeam
    ports:
      - 5002:5000
      - 5001:5001
    network_mode: bridge
    restart: 'no'

  sql:
    image: postgres:16.1
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=trader
      - POSTGRES_DB=stock_db
    ports:
      - "5432:5432"
    volumes:
      - stock_db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  stock_db: