"""recreate stock_price table

Revision ID: 023556f2348d
Revises: 79fe2f27645f
Create Date: 2023-12-03 01:12:48.306586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023556f2348d'
down_revision: Union[str, None] = '79fe2f27645f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('stock_id', 'dt')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_price')
    # ### end Alembic commands ###
