"""added symbol to stock

Revision ID: 288e936f1804
Revises: 092a5a42ce53
Create Date: 2023-12-06 23:23:04.283045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288e936f1804'
down_revision: Union[str, None] = '092a5a42ce53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('symbol', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'stock', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_column('stock', 'symbol')
    # ### end Alembic commands ###
