"""added numeric definition

Revision ID: 3808c21c53b8
Revises: a340a757d9ce
Create Date: 2023-12-09 01:11:10.355516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3808c21c53b8'
down_revision: Union[str, None] = 'a340a757d9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_price', 'close',
               existing_type=sa.NUMERIC(precision=16, scale=14),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    op.alter_column('stock_price', 'high',
               existing_type=sa.NUMERIC(precision=16, scale=14),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    op.alter_column('stock_price', 'low',
               existing_type=sa.NUMERIC(precision=16, scale=14),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_price', 'low',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.NUMERIC(precision=16, scale=14),
               existing_nullable=False)
    op.alter_column('stock_price', 'high',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.NUMERIC(precision=16, scale=14),
               existing_nullable=False)
    op.alter_column('stock_price', 'close',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.NUMERIC(precision=16, scale=14),
               existing_nullable=False)
    # ### end Alembic commands ###
