"""delete all tables

Revision ID: 39276eef81f3
Revises: 06029131e250
Create Date: 2023-12-06 22:44:38.776418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39276eef81f3'
down_revision: Union[str, None] = '06029131e250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop tables with foreign key references first
    op.drop_table('stock_strategy')
    op.drop_table('strategy')
    op.drop_table('stock_price')
    op.drop_table('stock')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price',
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('trade_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('vwap', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], name='stock_price_stock_id_fkey'),
    sa.PrimaryKeyConstraint('stock_id', 'dt', name='stock_price_pkey')
    )
    op.create_table('strategy',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('strategy_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='strategy_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_strategy_id', 'strategy', ['id'], unique=False)
    op.create_table('stock_strategy',
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], name='stock_strategy_stock_id_fkey'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], name='stock_strategy_strategy_id_fkey'),
    sa.PrimaryKeyConstraint('stock_id', 'strategy_id', name='stock_strategy_pkey')
    )
    op.create_table('stock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stock_pkey'),
    sa.UniqueConstraint('symbol', name='stock_symbol_key')
    )
    op.create_index('ix_stock_id', 'stock', ['id'], unique=False)
    # ### end Alembic commands ###
