"""added more precision to numbers

Revision ID: 4651addf987f
Revises: 53c7fb131f06
Create Date: 2023-12-09 01:02:42.197109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4651addf987f'
down_revision: Union[str, None] = '53c7fb131f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_price', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=16, scale=14),
               existing_nullable=False)
    op.alter_column('stock_price', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=16, scale=14),
               existing_nullable=False)
    op.alter_column('stock_price', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=16, scale=14),
               existing_nullable=False)
    op.alter_column('stock_price', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=16, scale=14),
               existing_nullable=False)
    op.alter_column('stock_price', 'volume',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_price', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('stock_price', 'open',
               existing_type=sa.Numeric(precision=16, scale=14),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('stock_price', 'low',
               existing_type=sa.Numeric(precision=16, scale=14),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('stock_price', 'high',
               existing_type=sa.Numeric(precision=16, scale=14),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('stock_price', 'close',
               existing_type=sa.Numeric(precision=16, scale=14),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
