"""add strategy and stock_strategy tables

Revision ID: 53c7fb131f06
Revises: 39f2842cbd4a
Create Date: 2023-12-07 15:53:58.091650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c7fb131f06'
down_revision: Union[str, None] = '39f2842cbd4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_id'), 'strategy', ['id'], unique=False)
    op.create_table('stock_strategy',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_id', 'strategy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_strategy')
    op.drop_index(op.f('ix_strategy_id'), table_name='strategy')
    op.drop_table('strategy')
    # ### end Alembic commands ###
