"""add new columns to stock_price

Revision ID: 6212ee492ee6
Revises: 023556f2348d
Create Date: 2023-12-03 11:08:45.683943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6212ee492ee6'
down_revision: Union[str, None] = '023556f2348d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_price', sa.Column('vwap', sa.Numeric(precision=6, scale=2), nullable=False))
    op.alter_column('stock_price', 'volume',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_price', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('stock_price', 'vwap')
    # ### end Alembic commands ###
