"""add exchange to stock table

Revision ID: 634e75e9feec
Revises: 68c1caf2d763
Create Date: 2023-12-04 17:41:52.722239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634e75e9feec'
down_revision: Union[str, None] = '68c1caf2d763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('exchange', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'exchange')
    # ### end Alembic commands ###
