"""remove trade count

Revision ID: 63e9d6312f10
Revises: 3808c21c53b8
Create Date: 2023-12-09 01:14:32.525342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e9d6312f10'
down_revision: Union[str, None] = '3808c21c53b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_price', 'close',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('stock_price', 'high',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('stock_price', 'low',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.drop_column('stock_price', 'trade_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_price', sa.Column('trade_count', sa.BIGINT(), autoincrement=False, nullable=False))
    op.alter_column('stock_price', 'low',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=False)
    op.alter_column('stock_price', 'high',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=False)
    op.alter_column('stock_price', 'close',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
