"""delete vw test

Revision ID: 87595250cc77
Revises: af0c70e37606
Create Date: 2023-12-03 00:56:28.893854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87595250cc77'
down_revision: Union[str, None] = 'af0c70e37606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_price', 'vwap')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_price', sa.Column('vwap', sa.NUMERIC(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
