"""re-create charts

Revision ID: 8f0818c5eacd
Revises: 7a1d69372028
Create Date: 2023-12-17 19:58:52.979547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f0818c5eacd'
down_revision: Union[str, None] = '7a1d69372028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backtest_charts_id', table_name='backtest_charts')
    op.drop_table('backtest_charts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_charts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chart_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest.id'], name='backtest_charts_backtest_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='backtest_charts_pkey')
    )
    op.create_index('ix_backtest_charts_id', 'backtest_charts', ['id'], unique=False)
    # ### end Alembic commands ###
