"""modify stock_prices table

Revision ID: 9565d288da51
Revises: bacb5004a640
Create Date: 2023-11-27 07:01:33.774720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9565d288da51'
down_revision: Union[str, None] = 'bacb5004a640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_price', sa.Column('trade_count', sa.Integer(), nullable=False))
    op.drop_column('stock_price', 'otc')
    op.drop_column('stock_price', 'transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_price', sa.Column('transactions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stock_price', sa.Column('otc', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('stock_price', 'trade_count')
    # ### end Alembic commands ###
