"""re-create profit-loss

Revision ID: a1e16cc4c826
Revises: 29a6969efb8b
Create Date: 2023-12-17 17:48:53.702509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e16cc4c826'
down_revision: Union[str, None] = '29a6969efb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backtest_profit_loss_id', table_name='backtest_profit_loss')
    op.drop_table('backtest_profit_loss')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_profit_loss',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_win', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('average_loss', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('compounding_annual_return', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('drawdown', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('expectancy', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('net_profit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sharpe_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sortino_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('probabilistic_sharpe_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('loss_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('win_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('profit_loss_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('alpha', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('beta', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('annual_standard_deviation', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('annual_variance', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('information_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('tracking_error', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('treynor_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('total_fees', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('estimated_strategy_capacity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('lowest_capacity_asset', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('portfolio_turnover', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('equity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fees', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('holdings', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('net_profit_runtime', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('probabilistic_sharpe_ratio_runtime', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_runtime', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('unrealized', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('volume', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest.id'], name='backtest_profit_loss_backtest_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='backtest_profit_loss_pkey')
    )
    op.create_index('ix_backtest_profit_loss_id', 'backtest_profit_loss', ['id'], unique=False)
    # ### end Alembic commands ###
