"""add technical indicators

Revision ID: ad6067d3fe32
Revises: 49b66877e05f
Create Date: 2023-12-15 14:39:16.299047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6067d3fe32'
down_revision: Union[str, None] = '49b66877e05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_price', sa.Column('sma20', sa.Numeric(), nullable=True))
    op.add_column('stock_price', sa.Column('sma50', sa.Numeric(), nullable=True))
    op.add_column('stock_price', sa.Column('rsi14', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_price', 'rsi14')
    op.drop_column('stock_price', 'sma50')
    op.drop_column('stock_price', 'sma20')
    # ### end Alembic commands ###
