"""re-create stock price table

Revision ID: af0c70e37606
Revises: a9bdbf8b5aba
Create Date: 2023-12-03 00:11:32.451977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0c70e37606'
down_revision: Union[str, None] = 'a9bdbf8b5aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('vwap', sa.Numeric(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'timestamp')
    )
    op.create_index(op.f('ix_stock_price_id'), 'stock_price', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_price_id'), table_name='stock_price')
    op.drop_table('stock_price')
    # ### end Alembic commands ###
