"""delete some columns

Revision ID: bab7dc5d2dfa
Revises: 68d5c3f444b8
Create Date: 2023-12-03 11:20:55.416262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab7dc5d2dfa'
down_revision: Union[str, None] = '68d5c3f444b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_price', 'transactions')
    op.drop_column('stock_price', 'vwap')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_price', sa.Column('vwap', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.add_column('stock_price', sa.Column('transactions', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
