"""remove stock_price table

Revision ID: d06910f254f0
Revises: 63e9d6312f10
Create Date: 2023-12-09 01:15:41.359789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd06910f254f0'
down_revision: Union[str, None] = '63e9d6312f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price',
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=16, scale=14), autoincrement=False, nullable=False),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], name='stock_price_stock_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_id', 'dt', name='stock_price_pkey')
    )
    # ### end Alembic commands ###
