"""delete volume and trans

Revision ID: d1374b761c65
Revises: 87595250cc77
Create Date: 2023-12-03 00:57:19.799469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1374b761c65'
down_revision: Union[str, None] = '87595250cc77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_price', 'trade_count')
    op.drop_column('stock_price', 'volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_price', sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('stock_price', sa.Column('trade_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
