"""add conid

Revision ID: e5b4350e25c6
Revises: ce209bba13a7
Create Date: 2023-12-06 23:48:39.774176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b4350e25c6'
down_revision: Union[str, None] = 'ce209bba13a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('conid', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'stock', ['conid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_column('stock', 'conid')
    # ### end Alembic commands ###
