"""re-define backest pk

Revision ID: fd43585c243f
Revises: 06c42eb4a3ac
Create Date: 2023-12-20 10:06:38.697986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd43585c243f'
down_revision: Union[str, None] = '06c42eb4a3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('backtest_stock_strategy_stock_id_stock_strategy_strategy_i_fkey', 'backtest', type_='foreignkey')
    op.drop_column('backtest', 'stock_strategy_stock_id')
    op.drop_column('backtest', 'stock_strategy_strategy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('stock_strategy_strategy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('backtest', sa.Column('stock_strategy_stock_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('backtest_stock_strategy_stock_id_stock_strategy_strategy_i_fkey', 'backtest', 'stock_strategy', ['stock_strategy_stock_id', 'stock_strategy_strategy_id'], ['stock_id', 'strategy_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
